# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/simulation_test/simulation_test.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/simulation_test/simulation_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Administrator/Desktop/simulation_test/simulation_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/Administrator/Desktop/simulation_test/simulation_test.srcs/sources_1/new/LED_igniting.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top LED_igniting -part xc7a35ticpg236-1L


write_checkpoint -force -noxdef LED_igniting.dcp

catch { report_utilization -file LED_igniting_utilization_synth.rpt -pb LED_igniting_utilization_synth.pb }
