# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivado_homework/MCPU/MCPU/MCPU.cache/wt [current_project]
set_property parent.project_path E:/vivado_homework/MCPU/MCPU/MCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/vivado_homework/MCPU/MCPU/MCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/control_unit.v
  E:/vivado_homework/MCPU/MCPU/MCPU.srcs/sources_1/new/jumpInsExtend.v
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/instructionMemory.v
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/addr_shift.v
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/Register.v
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/PC.v
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/Mux_signExtend.v
  E:/vivado_homework/MCPU/MCPU/MCPU.srcs/sources_1/new/Mux_WRdataSrc.v
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/Mux_RegDst.v
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/Mux_PCSrc.v
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/ALU_mem_to_reg.v
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/Mux_ALUSrc.v
  E:/vivado_homework/MCPU/MCPU/MCPU.srcs/sources_1/new/Mux_ALUSrcA.v
  E:/vivado_homework/MCPU/MCPU/MCPU.srcs/sources_1/new/IR.v
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/DataMemory.v
  E:/vivado_homework/MCPU/MCPU/MCPU.srcs/sources_1/new/DBDR.v
  E:/vivado_homework/MCPU/MCPU/MCPU.srcs/sources_1/new/BDR.v
  E:/vivado_homework/MCPU/MCPU/MCPU.srcs/sources_1/new/ALUoutDR.v
  E:/vivado_homework/MCPU/MCPU/MCPU.srcs/sources_1/new/ADR.v
  E:/vivado_homework/SCPU/project_1/project_1.srcs/sources_1/new/ALU.v
  E:/vivado_homework/MCPU/MCPU/MCPU.srcs/sources_1/new/MCPU.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top MCPU -part xc7a35tcpg236-1


write_checkpoint -force -noxdef MCPU.dcp

catch { report_utilization -file MCPU_utilization_synth.rpt -pb MCPU_utilization_synth.pb }
