set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clr]
set_property IOSTANDARD LVCMOS33 [get_ports dp]
set_property PACKAGE_PIN W7 [get_ports {a_to_g[6]}]
set_property PACKAGE_PIN W6 [get_ports {a_to_g[5]}]
set_property PACKAGE_PIN U8 [get_ports {a_to_g[4]}]
set_property PACKAGE_PIN V8 [get_ports {a_to_g[3]}]
set_property PACKAGE_PIN U5 [get_ports {a_to_g[2]}]
set_property PACKAGE_PIN V5 [get_ports {a_to_g[1]}]
set_property PACKAGE_PIN U7 [get_ports {a_to_g[0]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
set_property PACKAGE_PIN U2 [get_ports {an[0]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN V7 [get_ports dp]
set_property PACKAGE_PIN T17 [get_ports clr]


set_property PACKAGE_PIN L1 [get_ports led1]


set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]

set_property IOSTANDARD LVCMOS33 [get_ports pause]
set_property PACKAGE_PIN T18 [get_ports pause]

set_property IOSTANDARD LVCMOS33 [get_ports addOne]
set_property IOSTANDARD LVCMOS33 [get_ports carryOut]
set_property IOSTANDARD LVCMOS33 [get_ports set]
set_property IOSTANDARD LVCMOS33 [get_ports shift]
set_property PACKAGE_PIN U18 [get_ports addOne]
set_property PACKAGE_PIN W19 [get_ports carryOut]
set_property PACKAGE_PIN V17 [get_ports set]
set_property PACKAGE_PIN V16 [get_ports shift]

set_property IOSTANDARD LVCMOS33 [get_ports L]
set_property PACKAGE_PIN E19 [get_ports L]

set_property IOSTANDARD LVCMOS33 [get_ports L0]
set_property IOSTANDARD LVCMOS33 [get_ports L1]
set_property IOSTANDARD LVCMOS33 [get_ports L2]
set_property IOSTANDARD LVCMOS33 [get_ports L3]
set_property IOSTANDARD LVCMOS33 [get_ports L4]
set_property IOSTANDARD LVCMOS33 [get_ports L5]
set_property PACKAGE_PIN P1 [get_ports L1]
set_property PACKAGE_PIN N3 [get_ports L2]
set_property PACKAGE_PIN P3 [get_ports L3]

set_property IOSTANDARD LVCMOS33 [get_ports alarm_clock_mode]
set_property PACKAGE_PIN T1 [get_ports alarm_clock_mode]


set_property IOSTANDARD LVCMOS33 [get_ports L6]
set_property IOSTANDARD LVCMOS33 [get_ports L7]
set_property IOSTANDARD LVCMOS33 [get_ports L8]
set_property IOSTANDARD LVCMOS33 [get_ports L9]
set_property IOSTANDARD LVCMOS33 [get_ports L10]
set_property IOSTANDARD LVCMOS33 [get_ports L11]
set_property IOSTANDARD LVCMOS33 [get_ports L12]
set_property IOSTANDARD LVCMOS33 [get_ports L13]
set_property IOSTANDARD LVCMOS33 [get_ports L14]
set_property IOSTANDARD LVCMOS33 [get_ports L15]
set_property PACKAGE_PIN U3 [get_ports L4]
set_property PACKAGE_PIN W3 [get_ports L5]
set_property PACKAGE_PIN V3 [get_ports L6]
set_property PACKAGE_PIN V13 [get_ports L7]
set_property PACKAGE_PIN V14 [get_ports L8]
set_property PACKAGE_PIN U14 [get_ports L9]
set_property PACKAGE_PIN U15 [get_ports L10]
set_property PACKAGE_PIN W18 [get_ports L11]
set_property PACKAGE_PIN V19 [get_ports L12]
set_property PACKAGE_PIN U19 [get_ports L13]
set_property PACKAGE_PIN E19 [get_ports L14]
set_property PACKAGE_PIN U16 [get_ports L15]
set_property PACKAGE_PIN L17 [get_ports L0]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets set_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports choice]
set_property PACKAGE_PIN R2 [get_ports choice]
