set_property SRC_FILE_INFO {cfile:C:/Users/Administrator/Desktop/player/player/player.srcs/player/new/player.xdc rfile:../../../player.srcs/player/new/player.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports speaker]
