# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/学习/大二上学期/数字系统设计/vivado开发/ID_scrolliing/ID_scrolliing.cache/wt [current_project]
set_property parent.project_path E:/学习/大二上学期/数字系统设计/vivado开发/ID_scrolliing/ID_scrolliing.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/学习/大二上学期/数字系统设计/vivado开发/ID_scrolliing/ID_scrolliing.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/学习/大二上学期/数字系统设计/vivado开发/ID_scrolliing/ID_scrolliing.srcs/sources_1/new/scroll_top.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/学习/大二上学期/数字系统设计/vivado开发/ID_scrolliing/ID_scrolliing.srcs/constrs_1/new/ID_scrolling.xdc
set_property used_in_implementation false [get_files E:/学习/大二上学期/数字系统设计/vivado开发/ID_scrolliing/ID_scrolliing.srcs/constrs_1/new/ID_scrolling.xdc]


synth_design -top scroll_top -part xc7a35ticpg236-1L


write_checkpoint -force -noxdef scroll_top.dcp

catch { report_utilization -file scroll_top_utilization_synth.rpt -pb scroll_top_utilization_synth.pb }
